variables:
  GIT_STRATEGY: none
  image_aduulm_rolling: mrm-git.e-technik.uni-ulm.de:4567/aduulm/docker_images/aduulm-ros2-rolling:latest
  image_aduulm_jazzy: mrm-git.e-technik.uni-ulm.de:4567/aduulm/docker_images/aduulm-ros2-jazzy:latest

stages:
  - library
  - library_test
  - ros

.build_library:
  stage: library
  script:
    - build_repo_with_dependencies_ros2.sh release aduulm_launch_lib

build_library_jazzy:
  extends: .build_library
  image: $image_aduulm_jazzy

build_library_rolling:
  extends: .build_library
  image: $image_aduulm_rolling

.test_library:
  stage: library_test
  artifacts:
    when: always
    expire_in: 2 days
    reports:
      junit: report_lib_*.xml
  coverage: /^\s*lines:\s*\d+.\d+\%/
  script:
    - build_repo_with_dependencies_ros2.sh coverage aduulm_launch_lib
    - source ./colcon_build/install/setup.bash
    - pytest src/aduulm_launch/library/test/python --junitxml=report_lib_python.xml

test_library_jazzy:
  extends: .test_library
  needs: [build_library_jazzy]
  image: $image_aduulm_jazzy

test_library_rolling:
  extends: .test_library
  needs: [build_library_rolling]
  image: $image_aduulm_rolling

.build_ros:
  stage: ros
  artifacts:
    expire_in: 2 days
    reports:
      junit: report_ros_python.xml
  script:
    # delete any src folders that are still around from previous runs
    - rm -rf src
    - source gitlab-ros.sh
    # create colcon workspace with all dependencies
    - setup_repo_workspace_with_dependencies.sh
    # make source folders older than the build/devel folders so that make will not rebuild the targets
    - find ./src -exec touch -t 202001010000 {} \;
    # build only missing packages
    - build_colcon_workspace.sh release aduulm_launch
    - source ./colcon_build/install/setup.bash
    - pytest src/aduulm_launch/ros2/test/python --junitxml=report_ros_python.xml

build_ros_jazzy:
  extends: .build_ros
  image: $image_aduulm_jazzy

build_ros_rolling:
  extends: .build_ros
  image: $image_aduulm_rolling
